# Generated by Django 4.1 on 2025-07-27 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_actor_cinemahall_genre_alter_movie_duration_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cinemahall',
            old_name='seating_in_row',
            new_name='seats_in_row',
        ),
    ]
